from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1196, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1161, 791))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.turbidity = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.turbidity.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.turbidity.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.turbidity.setText("")
        self.turbidity.setPixmap(QtGui.QPixmap("images/new.png"))
        self.turbidity.setObjectName("turbidity")
        self.verticalLayout.addWidget(self.turbidity)
        self.hightlight = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.hightlight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hightlight.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.hightlight.setText("")
        self.hightlight.setPixmap(QtGui.QPixmap("images/highlights.png"))
        self.hightlight.setObjectName("hightlight")
        self.verticalLayout.addWidget(self.hightlight)
        self.brillance = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.brillance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.brillance.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.brillance.setText("")
        self.brillance.setPixmap(QtGui.QPixmap("images/brilliance.png"))
        self.brillance.setObjectName("brillance")
        self.verticalLayout.addWidget(self.brillance)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mirror = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.mirror.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mirror.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.mirror.setText("")
        self.mirror.setPixmap(QtGui.QPixmap("images/mirror.png"))
        self.mirror.setObjectName("mirror")
        self.verticalLayout_4.addWidget(self.mirror)
        self.rotate_90 = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.rotate_90.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rotate_90.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.rotate_90.setText("")
        self.rotate_90.setPixmap(QtGui.QPixmap("images/rotate_90.png"))
        self.rotate_90.setObjectName("rotate_90")
        self.verticalLayout_4.addWidget(self.rotate_90)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_1 = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.label_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.verticalLayout_2.addWidget(self.label_1)
        self.label_2 = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.label_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.label_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_6 = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.label_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_4 = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.label_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.label_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.imageplace = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.imageplace.setText("")
        self.imageplace.setObjectName("imageplace")
        self.horizontalLayout_3.addWidget(self.imageplace)
        self.main_tools = QtWidgets.QVBoxLayout()
        self.main_tools.setContentsMargins(20, 20, 20, 20)
        self.main_tools.setObjectName("main_tools")
        self.filters = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.filters.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.filters.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.filters.setText("")
        self.filters.setPixmap(QtGui.QPixmap("images/filters.png"))
        self.filters.setObjectName("filters")
        self.main_tools.addWidget(self.filters)
        self.reverse = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.reverse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reverse.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.reverse.setText("")
        self.reverse.setPixmap(QtGui.QPixmap("images/move_wrap.png"))
        self.reverse.setObjectName("reverse")
        self.main_tools.addWidget(self.reverse)
        self.edits = QPushButton_with_image(self.verticalLayoutWidget_3)
        self.edits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edits.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.edits.setText("")
        self.edits.setPixmap(QtGui.QPixmap("images/edit.png"))
        self.edits.setObjectName("edits")
        self.main_tools.addWidget(self.edits)
        self.horizontalLayout_3.addLayout(self.main_tools)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.valuegforeditor = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.valuegforeditor.setMaximum(15)
        self.valuegforeditor.setPageStep(1)
        self.valuegforeditor.setOrientation(QtCore.Qt.Horizontal)
        self.valuegforeditor.setObjectName("valuegforeditor")
        self.verticalLayout_3.addWidget(self.valuegforeditor)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1196, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openphotoact = QtWidgets.QAction(MainWindow)
        self.openphotoact.setCheckable(True)
        self.openphotoact.setObjectName("openphotoact")
        self.newphotoact = QtWidgets.QAction(MainWindow)
        self.newphotoact.setCheckable(True)
        self.newphotoact.setObjectName("newphotoact")
        self.deletephotoact = QtWidgets.QAction(MainWindow)
        self.deletephotoact.setCheckable(True)
        self.deletephotoact.setObjectName("deletephotoact")
        self.closephotoact = QtWidgets.QAction(MainWindow)
        self.closephotoact.setCheckable(True)
        self.closephotoact.setObjectName("closephotoact")
        self.renamephotoact = QtWidgets.QAction(MainWindow)
        self.renamephotoact.setCheckable(True)
        self.renamephotoact.setObjectName("renamephotoact")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.savephotoact = QtWidgets.QAction(MainWindow)
        self.savephotoact.setCheckable(True)
        self.savephotoact.setObjectName("savephotoact")
        self.menu.addAction(self.openphotoact)
        self.menu.addAction(self.renamephotoact)
        self.menu.addAction(self.savephotoact)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.openphotoact.setText(_translate("MainWindow", "Open"))
        self.openphotoact.setWhatsThis(_translate("MainWindow", "Ctrl+O"))
        self.openphotoact.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.newphotoact.setText(_translate("MainWindow", "New..."))
        self.newphotoact.setWhatsThis(_translate("MainWindow", "Ctrl+N"))
        self.newphotoact.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.deletephotoact.setText(_translate("MainWindow", "Delete"))
        self.deletephotoact.setWhatsThis(_translate("MainWindow", "Ctrl+D"))
        self.deletephotoact.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.closephotoact.setText(_translate("MainWindow", "Close"))
        self.renamephotoact.setText(_translate("MainWindow", "Rename"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setWhatsThis(_translate("MainWindow", "Ctrl+Z"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionCopy.setText(_translate("MainWindow", "Redo"))
        self.actionCopy.setWhatsThis(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionPaste.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setWhatsThis(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.savephotoact.setText(_translate("MainWindow", "Save"))
        self.savephotoact.setWhatsThis(_translate("MainWindow", "Ctlr+S"))
        self.savephotoact.setShortcut(_translate("MainWindow", "Ctrl+S"))
from QLabel import QPushButton_with_image
